export const GET_STUDENTS = 'GET_STUDENTS'
export const CALCULATE_GRADE = 'CALCULATE_GRADE'
export const VALIDATE_FIELD = 'VALIDATE_FIELD'
export const INITIALIZE_VALIDATED_COMPONENT = 'INITIALIZE_VALIDATED_COMPONENT'